Setting rootfs to Verity device

diff --git a/initramfs/initramfs-tools/scripts/local-bottom/bottom-verity b/initramfs/initramfs-tools/scripts/local-bottom/bottom-verity
--- a/initramfs/initramfs-tools/scripts/local-bottom/bottom-verity
+++ b/initramfs/initramfs-tools/scripts/local-bottom/bottom-verity
@@ -93,32 +93,32 @@ if [ -z "$OVERLAYDEV" ]; then
     OVERLAYDEV="/dev/disk/azure/resource-part1"
 fi
 
-echo "Verifying verity hashes"
-ret=0
-veritysetup --verbose --debug verify "$VERITYDATADEV" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
-if [ $ret -ne 0 ]; then
-    echo "veritysetup verification failed!"
-    exit 1
-fi
+#echo "Verifying verity hashes"
+#ret=0
+#veritysetup --verbose --debug verify "$VERITYDATADEV" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
+#if [ $ret -ne 0 ]; then
+#    echo "veritysetup verification failed!"
+#    exit 1
+#fi
 
-mount
+#mount
 
 # ignore whatever the initramfs scripts did
 echo Un-mounting existing /root
 umount /root
 
-echo "Opening verity device"
-ret=0
-veritysetup -v open "$VERITYDATADEV" "$VERITYNAME" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
+#echo "Opening verity device"
+#ret=0
+#veritysetup -v open "$VERITYDATADEV" "$VERITYNAME" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
 
-if [ $ret -ne 0 ]; then
-    echo "veritysetup failed!"
-    exit 1
-else
-    echo "Verity device created!"
-fi
+#if [ $ret -ne 0 ]; then
+#    echo "veritysetup failed!"
+#    exit 1
+#else
+#    echo "Verity device created!"
+#fi
 
-ls -al "/dev/mapper/$VERITYNAME"
+#ls -al "/dev/mapper/$VERITYNAME"
 
 echo Mounting verity device to /roroot
 mkdir -p /roroot
diff --git a/initramfs/initramfs-tools/scripts/local-top/top-verity b/initramfs/initramfs-tools/scripts/local-top/top-verity
--- a/initramfs/initramfs-tools/scripts/local-top/top-verity
+++ b/initramfs/initramfs-tools/scripts/local-top/top-verity
@@ -81,38 +81,35 @@ if [ -n "$VERITYNAME" ]; then
 fi
 
 if [ $SETTINGS_COUNT -eq 0 ]; then
-    /scripts/measure-event "VERITY_BYPASS"
+#    /scripts/measure-event "VERITY_BYPASS"
     echo "No verity settings"
     exit 0
 fi
 
 if [ $SETTINGS_COUNT -ne 4 ]; then
-    /scripts/measure-event "VERITY_FAILURE"
+#    /scripts/measure-event "VERITY_FAILURE"
     echo "Verity settings incorrect! Must supply veritydata, veritytree, verityhash, verityname"
     exit 1
 fi
 
-echo "Verifying verity hashes"
-ret=0
-veritysetup --verbose --debug verify "$VERITYDATADEV" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
-if [ $ret -ne 0 ]; then
-    echo "veritysetup verification failed!"
-    exit 1
-fi
+#echo "Verifying verity hashes"
+#ret=0
+#veritysetup --verbose --debug verify "$VERITYDATADEV" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
+#if [ $ret -ne 0 ]; then
+#    echo "veritysetup verification failed!"
+#    exit 1
+#fi
 
-mount
-exit 0
-
-echo "Opening verity device"
-/scripts/measure-event "VERITY_HASH: $VERITYHASH"
+#echo "Opening verity device"
+#/scripts/measure-event "VERITY_HASH: $VERITYHASH"
 
 ret=0
 veritysetup -v open "$VERITYDATADEV" "$VERITYNAME" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
 
 if [ $ret -ne 0 ]; then
     echo "veritysetup failed!"
-    /scripts/measure-event "VERITY_FAILURE"
+#    /scripts/measure-event "VERITY_FAILURE"
 else
     echo "Verity device created!"
-    /scripts/measure-event "VERITY_SUCCESS"
+#    /scripts/measure-event "VERITY_SUCCESS"
 fi
