Disable verification

diff --git a/initramfs/initramfs-tools/scripts/local-top/top-verity b/initramfs/initramfs-tools/scripts/local-top/top-verity
--- a/initramfs/initramfs-tools/scripts/local-top/top-verity
+++ b/initramfs/initramfs-tools/scripts/local-top/top-verity
@@ -92,13 +92,13 @@ if [ $SETTINGS_COUNT -ne 4 ]; then
     exit 1
 fi
 
-echo "Verifying verity hashes for $VERITYDATADEV $VERITYTREEDEV $VERITYHASH $VERITYNAME"
-ret=0
-veritysetup --verbose --debug verify "$VERITYDATADEV" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
-if [ $ret -ne 0 ]; then
-    echo "veritysetup verification failed!"
-    exit 1
-fi
+#echo "Verifying verity hashes"
+#ret=0
+#veritysetup --verbose --debug verify "$VERITYDATADEV" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
+#if [ $ret -ne 0 ]; then
+#    echo "veritysetup verification failed!"
+#    exit 1
+#fi
 
 echo "Opening verity device"
 /scripts/measure-event "VERITY_HASH: $VERITYHASH"
